//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEMO
    {
        public int ID { get; set; }
        public int seq { get; set; }
        public string sec { get; set; }
        public string course { get; set; }
        public string faculty { get; set; }
    }
}
