//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public schedule()
        {
            this.WeekWises = new HashSet<WeekWise>();
        }
    
        public int schid { get; set; }
        public Nullable<int> offid { get; set; }
        public Nullable<int> slotid { get; set; }
        public Nullable<int> occupied { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> CTId { get; set; }
        public Nullable<int> SId { get; set; }
    
        public virtual ClassType ClassType { get; set; }
        public virtual offeredcourse offeredcourse { get; set; }
        public virtual slot slot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeekWise> WeekWises { get; set; }
        public virtual Semester Semester { get; set; }
    }
}
