//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sectiondetail
    {
        public int sdid { get; set; }
        public Nullable<int> offid { get; set; }
        public Nullable<int> secid { get; set; }
    
        public virtual offeredcourse offeredcourse { get; set; }
    }
}
