//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class slottype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public slottype()
        {
            this.slots = new HashSet<slot>();
        }
    
        public int slottypeid { get; set; }
        public string duration { get; set; }
        public Nullable<System.TimeSpan> ClassStartTime { get; set; }
        public Nullable<int> BreakDuration { get; set; }
        public Nullable<System.TimeSpan> ClassEndTime { get; set; }
        public Nullable<int> slotno { get; set; }
        public Nullable<int> slottype1 { get; set; }
        public Nullable<int> subslot { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<slot> slots { get; set; }
    }
}
