//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vschedule
    {
        public int schid { get; set; }
        public Nullable<int> offid { get; set; }
        public Nullable<int> slotid { get; set; }
        public Nullable<int> courseid { get; set; }
        public int secid { get; set; }
        public string sectionname { get; set; }
        public Nullable<int> occupied { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public int teacherid { get; set; }
        public string teachername { get; set; }
        public int dayid { get; set; }
        public int slottypeid { get; set; }
        public int roomid { get; set; }
        public string duration { get; set; }
        public Nullable<int> slotno { get; set; }
        public int subslotid { get; set; }
        public Nullable<System.TimeSpan> ClassStartTime { get; set; }
        public Nullable<int> BreakDuration { get; set; }
        public Nullable<System.TimeSpan> ClassEndTime { get; set; }
        public string dayname { get; set; }
        public string roomno { get; set; }
        public string campus { get; set; }
        public Nullable<int> SchCTId { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string Year { get; set; }
        public bool flag { get; set; }
        public System.DateTime SemesterStartDate { get; set; }
        public System.DateTime SemesterEndDate { get; set; }
        public string SType { get; set; }
        public Nullable<int> SID { get; set; }
        public int PId { get; set; }
        public string Program { get; set; }
        public int ClassID { get; set; }
        public string Class { get; set; }
        public string section { get; set; }
    }
}
