//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeekWise
    {
        public int WId { get; set; }
        public int schid { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Week_no { get; set; }
        public Nullable<System.TimeSpan> ClassStarted { get; set; }
        public Nullable<int> BreakDuration { get; set; }
        public Nullable<System.TimeSpan> ClassEnded { get; set; }
        public int CTId { get; set; }
    
        public virtual ClassType ClassType { get; set; }
        public virtual schedule schedule { get; set; }
    }
}
